// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvBFLGqQ59FI15nTFC8mN3VfiJcgRgQdk',
    appId: '1:563438115838:web:2ecec443e841b360b4beaf',
    messagingSenderId: '563438115838',
    projectId: 'spidertack',
    authDomain: 'spidertack.firebaseapp.com',
    storageBucket: 'spidertack.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj6szhUIa4oUxtiLUAMqzjcExf__CAo7Q',
    appId: '1:563438115838:android:84dbd539c4a13acbb4beaf',
    messagingSenderId: '563438115838',
    projectId: 'spidertack',
    storageBucket: 'spidertack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsRJsqWoil21q4oY_nnTy5d-6ubZv9Jj0',
    appId: '1:563438115838:ios:bc9a92408f4fb9c8b4beaf',
    messagingSenderId: '563438115838',
    projectId: 'spidertack',
    storageBucket: 'spidertack.firebasestorage.app',
    iosBundleId: 'com.example.spidertrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsRJsqWoil21q4oY_nnTy5d-6ubZv9Jj0',
    appId: '1:563438115838:ios:bc9a92408f4fb9c8b4beaf',
    messagingSenderId: '563438115838',
    projectId: 'spidertack',
    storageBucket: 'spidertack.firebasestorage.app',
    iosBundleId: 'com.example.spidertrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvBFLGqQ59FI15nTFC8mN3VfiJcgRgQdk',
    appId: '1:563438115838:web:8e91636f331242aeb4beaf',
    messagingSenderId: '563438115838',
    projectId: 'spidertack',
    authDomain: 'spidertack.firebaseapp.com',
    storageBucket: 'spidertack.firebasestorage.app',
  );
}
